// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2anv7Dup5yMIaXCwD5fGPlB6kXNk9UI',
    appId: '1:782717928410:web:9cdc57ed05b1284c1836e3',
    messagingSenderId: '782717928410',
    projectId: 'hotel-booking-app-88ff8',
    authDomain: 'hotel-booking-app-88ff8.firebaseapp.com',
    storageBucket: 'hotel-booking-app-88ff8.firebasestorage.app',
    measurementId: 'G-Y60HF546Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kEDsa8b1qL0mWWc82Vt4Kwzgw7cJ85Y',
    appId: '1:782717928410:android:f5e8c58b932205281836e3',
    messagingSenderId: '782717928410',
    projectId: 'hotel-booking-app-88ff8',
    storageBucket: 'hotel-booking-app-88ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fhPnyzu-Lxqa5-P-JdgtjJMNel3MI2E',
    appId: '1:782717928410:ios:49d1010f29f4c4661836e3',
    messagingSenderId: '782717928410',
    projectId: 'hotel-booking-app-88ff8',
    storageBucket: 'hotel-booking-app-88ff8.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0fhPnyzu-Lxqa5-P-JdgtjJMNel3MI2E',
    appId: '1:782717928410:ios:49d1010f29f4c4661836e3',
    messagingSenderId: '782717928410',
    projectId: 'hotel-booking-app-88ff8',
    storageBucket: 'hotel-booking-app-88ff8.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS2anv7Dup5yMIaXCwD5fGPlB6kXNk9UI',
    appId: '1:782717928410:web:9059dde73e3599b81836e3',
    messagingSenderId: '782717928410',
    projectId: 'hotel-booking-app-88ff8',
    authDomain: 'hotel-booking-app-88ff8.firebaseapp.com',
    storageBucket: 'hotel-booking-app-88ff8.firebasestorage.app',
    measurementId: 'G-7LLBVBXLD6',
  );
}
