// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYy8n7Vbl6V8WaT0bOy0FSB6G_8C_-Ld8',
    appId: '1:881780406764:web:65739fc44317087ed968c9',
    messagingSenderId: '881780406764',
    projectId: 'hotel-booking-and-review-app',
    authDomain: 'hotel-booking-and-review-app.firebaseapp.com',
    storageBucket: 'hotel-booking-and-review-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdKLK7uUI3CalVpZvU9F39gLROeKgwXg',
    appId: '1:881780406764:android:ec1570cdd27b768cd968c9',
    messagingSenderId: '881780406764',
    projectId: 'hotel-booking-and-review-app',
    storageBucket: 'hotel-booking-and-review-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSxRtOKvT9N99pzYqJm7lk6RfOpWD5K4',
    appId: '1:881780406764:ios:73b68aacf87d2548d968c9',
    messagingSenderId: '881780406764',
    projectId: 'hotel-booking-and-review-app',
    storageBucket: 'hotel-booking-and-review-app.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingAndReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgSxRtOKvT9N99pzYqJm7lk6RfOpWD5K4',
    appId: '1:881780406764:ios:73b68aacf87d2548d968c9',
    messagingSenderId: '881780406764',
    projectId: 'hotel-booking-and-review-app',
    storageBucket: 'hotel-booking-and-review-app.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingAndReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYy8n7Vbl6V8WaT0bOy0FSB6G_8C_-Ld8',
    appId: '1:881780406764:web:e40cd366988ab634d968c9',
    messagingSenderId: '881780406764',
    projectId: 'hotel-booking-and-review-app',
    authDomain: 'hotel-booking-and-review-app.firebaseapp.com',
    storageBucket: 'hotel-booking-and-review-app.firebasestorage.app',
  );
}
